In [ ]:
arreglo_cincos = np.full(10, 5)
print(arreglo_cincos)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
import numpy as np

In [ ]:
arreglo_cincos = np.full(10, 5)
print(arreglo_cincos)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
arreglo_pares = np.arange(10, 51, 2)
print(arreglo_pares)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
matriz=np.random.randint(0, 100, (4, 4))
print(matriz)

[[94 67 49 88]
 [29 73 41 18]
 [50 23 58  5]
 [61 44 82 16]]


In [ ]:
arreglo_rand = np.random.rand(10)
suma = np.sum(arreglo_rand)
print("Arreglo:", arreglo_rand)
print("Suma:", suma)

Arreglo: [0.28875584 0.29135159 0.70147287 0.29985369 0.67920191 0.55398264
 0.15126429 0.55869265 0.17984782 0.67863955]
Suma: 4.383062832139934


In [ ]:
arreglo_rand2 = np.random.rand(10)
media = np.mean(arreglo_rand2)
print("Arreglo:", arreglo_rand2)
print("Media:", media)

Arreglo: [0.85547966 0.87207187 0.92898437 0.26396488 0.80177675 0.29272722
 0.03803702 0.58242261 0.18987095 0.46441299]
Media: 0.5289748321974577
